### ISSUE TITLE
Remove "tomaskral/nonroot-nginx" to "nginx"

### ISSUE THREAD

**Issue by cdrage** [redhat-developer/opencompose#152]
We should use the more universal nginx container (the official one from Docker hub).

**Comment by kadel** [comment]
The thing is that `tomaskral/nonroot-nginx` will work also on openshift ;-) Official won't.

I don't care about this particular image, but it should be something that doesn't run as root inside the container.

We don't have support for OpenShift yet, but once we have we will have to change all examples or create new/special for openshift.
