### ISSUE TITLE
Allow specifying replica count for service

### ISSUE THREAD

**Issue by tnozicka** [redhat-developer/opencompose#19]
OpenCompose user should be allowed to specify number of replicas for the service to be able to scale it.

Proposal: Add an *optional* field named `replicas` into `ServiceSpec`. It defaults to value `1` and it should map into generated deployment under [DeploymentSpec.replicas](https://kubernetes.io/docs/api-reference/v1.5/#deploymentspec-v1beta1)

**Comment by surajssd** [comment]
I would like to work on it :)

**Comment by kadel** [comment]
> Proposal: Add an optional field named replicas into ServiceSpec. It defaults to value 1 and it should map into generated deployment under DeploymentSpec.replicas

This might be a little bit more trickier. I don't think we should default to 1.
If `replicas` is not set in OpenCompose file, than it should be also unset in generated `PodSpec`.

Replica count might be different on the server from what is specified in OpenCompose file. 
If you default to `replicas: 1` it will always overwrite replica number when doing `kubectl apply`.
In some cases this might cause problems (for example when  using AutoScaler)

I think `replicas` in OpenCompose should directly map to PodSpec. If it is unset, than it shouldn't be set in PodSpec. If it is explicitly set to 0 than also in PodSpec should be 0.
