### ISSUE TITLE
Support for storage (volume mounts)

### ISSUE THREAD

**Issue by tnozicka** [redhat-developer/opencompose#25]
OpenCompose file should allow user to specify volume (storage) mounts for services.

E.g. w/o it, the [wordpress example](https://github.com/redhat-developer/opencompose/blob/master/examples/wordpress/no-storage.yml) now looses all the data if database container is restarted.

Ref:
 - https://kubernetes.io/docs/tasks/configure-pod-container/configure-volume-storage/
 - https://kubernetes.io/docs/tasks/configure-pod-container/configure-persistent-volume-storage/

**Comment by surajssd** [comment]
Created a proposal for this, before going onto implementation, https://github.com/redhat-developer/opencompose/pull/79
