### ISSUE TITLE
Zsh completion support

### ISSUE THREAD

**Issue by tnozicka** [redhat-developer/opencompose#28]
At this point OpenCompose is missing completion support for `Zsh`. It would be nice to add it to complement `Bash` completion we already have. The `Bash` completion doesn't work for users running `Zsh`.

I have seen some similar work in kubectl which could serve as inspiration.

**Comment by cdrage** [comment]
@tnozicka Check out the work I did for Kompose :)

**Comment by tnozicka** [comment]
@cdrage I know about it but I didn't think you did more than `s/kubectl/kompose/`. Honestly I just didn't have time to investigate it properly yet. It would help us plan for this feature if you could comfirm that it's just about taking the bellow mentioned kubectl code.

Ref:
 - [Kompose Zsh completion](https://github.com/kubernetes-incubator/kompose/blob/816b74811d4b4d0a8afb46a2d3d4af5588b6b1b3/cmd/completion.go#L72-L223)
 - [Kubectl Zsh completion](https://github.com/kubernetes/kubernetes/blob/9dec47d/pkg/kubectl/cmd/completion.go#L135-L299) the original one I was mentioning

**Comment by cdrage** [comment]
Yup, it is the same. With the exception of me changing the name from zsh_tail to zshTail since go lint was complaining.

**Comment by tnozicka** [comment]
@cdrage Thanks. Now that you confirmed it's just about taking that snippet I'll look at it sooner since this shouldn't take much of my time. And I actually use Zsh :)

**Comment by tnozicka** [comment]
For the record: spf13/cobra has an old [issue](https://github.com/spf13/cobra/issues/107) about Zsh autocompletion. We'll go for that kubectl hack because the issues isn't moving anywhere.
