### ISSUE TITLE
Support for repeating tasks (CronJobs)

### ISSUE THREAD

**Issue by tnozicka** [redhat-developer/opencompose#44]
When describing applications user sometimes needs to define an action that happens one a time. Kubernetes now has CronJobs for exactly this purpose and we should allow OpenCompose users to define it.

Ref:
 - https://kubernetes.io/docs/user-guide/cron-jobs/
 - https://github.com/kubernetes/community/blob/master/contributors/design-proposals/cronjob.md

**Comment by surajssd** [comment]
@tnozicka @kadel can someone tell me why support CronJobs over Jobs? Is it because Job is a special usecase of CronJob?
