### ISSUE TITLE
Support for multiple delivery environments

### ISSUE THREAD

**Issue by tnozicka** [redhat-developer/opencompose#47]
OpenCompose user should be able to describe his application in one place and than apply separate configurations for his environment like dev, test, prod, ...

This can be done in multiple ways. One of them would be by merging multiple OpenCompose files.

(Needs more investigation.)

**Comment by jstrachan** [comment]
In my experience different people are in charge of the different resources. e.g. the app developer creates and maintains the main application YAML which is identical in all environments. Then each environment is managed by some Ops person who then owns and configures the environment specific stuff (e.g. PVs / Secrets / custom ConfigMap changes  / OpenShift Template or Helm parameters).

e.g. team A and B may generate separate apps to be deployed together, then separate Ops team may configure `Pre-Prod` and `Prod` environment resources. In this case you probably want 2 git repos and release processes for team A and B; then a separate git repo / branch or each environment (`Pre-Prod` or `Prod`).

We worked this way making https://openshift.io/ and deal with microservices releasing apps and then ops teams managing environment specific stuff like secrets.

Given this is a cross cutting concern; am not sure if opencompose is the tool to fix CI / CD and multi-team workflow and control - but rather allow it to work in whatever git / team / workflow / pipeline folks choose. 

e.g. allowing environment specific stuff to be managed somehow (e.g. separate git repos) and then have the opencompose generate the common YAML thats shared between environments

**Comment by kadel** [comment]
> Given this is a cross cutting concern; am not sure if opencompose is the tool to fix CI / CD and multi-team workflow and control - but rather allow it to work in whatever git / team / workflow / pipeline folks choose.

Completely agree. This what we are trying to do.
