### ISSUE TITLE
No output on successul conversion

### ISSUE THREAD

**Issue by concaf** [redhat-developer/opencompose#57]
Successful conversion does not print any success message, which would be helpful to have.
A list of the files created and the next steps could help.

**Comment by tnozicka** [comment]
@containscafeine Thanks for filing the issue. We talked about this sometime ago with @kadel but haven't addressed it yet. I'll take a look.

**Comment by kadel** [comment]
How about changing default behavior and print  output to stdout by default?

if `--output-dir` is not set, print to stdout.
if `--outdir-dir` is set, save files to directory.

**Comment by tnozicka** [comment]
@kadel I don't think it's connected to this issue. Even then we will be writing files and we should tell it to user.

**Comment by kadel** [comment]
ok, I thought that it might be connected to this :blush:.
Separate issue needs to be created than
