### ISSUE TITLE
Using "-" for stdout?

### ISSUE THREAD

**Issue by concaf** [redhat-developer/opencompose#61]
Hi,

Currently when `--output-dir` is set to `-` then we print the output to STDOUT, but generally in other CLI tools I have used, `-` is generally used to accept input from STDIN.

I could be totally wrong, but this looked a bit out of place with how I have been using other tools.

Thoughts?

**Comment by tnozicka** [comment]
@containscafeine My feeling was that it means `not a file` so you can use it for both `stdin` and `stdout`. I am open to suggestions on how to handle it differently if it would be an issue.

**Comment by surajssd** [comment]
This is done!
