### ISSUE TITLE
Add support for multiple file inputs?

### ISSUE THREAD

**Issue by concaf** [redhat-developer/opencompose#62]
$SUBJECT

**Comment by tnozicka** [comment]
Yes, it is planned :) Now we can track it in an issue.
https://github.com/redhat-developer/opencompose/blob/master/pkg/cmd/convert.go#L84

**Comment by surajssd** [comment]
will this be just adding services from multiple files and converting it, or will this also be a merge of objects like `kompose` does?

**Comment by tnozicka** [comment]
we had some notion of merging objects but no decision has been made yet. we will discuss it once the more pressing issues are addressed

**Comment by tnozicka** [comment]
actually, a duplicate of https://github.com/redhat-developer/opencompose/issues/47
