### ISSUE TITLE
`opencompose convert -f -` should accept input from STDIN?

### ISSUE THREAD

**Issue by concaf** [redhat-developer/opencompose#63]
$SUBJECT

**Comment by tnozicka** [comment]
yes, it should; it's just not implemented yet

**Comment by concaf** [comment]
@tnozicka picking this up

**Comment by tnozicka** [comment]
also I think that `kubectl` and `oc` do the same with not specifying `-f` (`-f=""`)

generally we want the same behaviour as there have so ideally look into their source code
