### ISSUE TITLE
Change the file naming convention to <service_name>-<object_type>

### ISSUE THREAD

**Issue by surajssd** [redhat-developer/opencompose#65]
Right now if I run opencompose cli tool:
```bash
opencompose convert -f hello-nginx.yaml
```
The files generated are:
```
deployment-helloworld.yaml
service-helloworld.yaml
```

Which is hard to search visually when there are multiple files generated due to multiple services.

For e.g. when there are more than 5 services then while feeding some file of service i will have to do is Deployment.<service-name>, as opposed to what I can do with the proposed implementation is that I can type service name and tab tab I can see what all files are generated for that service.

Let's group the files on basis of service names and not kubernetes types.

**Comment by kadel** [comment]
I believe this is duplicate of https://github.com/redhat-developer/opencompose/issues/58

**Comment by surajssd** [comment]
@kadel yes it is duplicate sorry about that! closing!
