### ISSUE TITLE
Add cross compilation support to release tooling

### ISSUE THREAD

**Issue by tnozicka** [redhat-developer/opencompose#71]
We need to extend our release tooling with cross compilation support.

**Comment by surajnarwade** [comment]
@kadel , I think we have this support now ?

**Comment by kadel** [comment]
I don't think so. Our tooling is still building just for current platform

**Comment by cdrage** [comment]
@kadel @surajnarwade 
Bit confused what this may mean, I've release ARM / AMD64 / macOS / Windows here: https://github.com/redhat-developer/opencompose/releases and within our release tooling it's compiled using `make cross` which uses:

```
  gox -osarch="darwin/amd64 linux/amd64 linux/arm windows/amd64" -output="bin/opencompose-{{.OS}}-{{.Arch}}" $(GO_LDFLAGS)
```

I think we can close this?

**Comment by kadel** [comment]
ahhh, my bad. Didn't noticed that there already is `make cross`

**Comment by kadel** [comment]
@surajnarwade is right, we can close this
