### ISSUE TITLE
if no option for output is specified, print to stdout

### ISSUE THREAD

**Issue by kadel** [redhat-developer/opencompose#80]
How about changing default behavior and print output to stdout by default?

if --output-dir is not set, print to stdout.
if --outdir-dir is set, save files to directory.

**Comment by tnozicka** [comment]
I am not sure what the correct default should be - are there any examples from other project on the default behaviour is in similar cases?

**Comment by tnozicka** [comment]
I am slightly inclined to having default to:
a) print to stdout
b) require user to specify it explicitly - meaning the default would be an error with suggestions on `--outdir-dir -` for stdout or `--outdir-dir .` for current directory

By default witting several files into current directory might mess up with existing files. (Although printing **a lot** of gibberish to scroll terminal several times is not ideal as well.)

**Comment by surajssd** [comment]
+1 for default to stdout also we need to rename that `--output-dir` to something better because it is not the only thing it does by name which says output in a directory!

**Comment by tnozicka** [comment]
I don't believe we need to rename. This is fairly similar to what k8s does. `--file=-` means stdin

**Comment by tnozicka** [comment]
and actually `--output-dir=-` say that "it won't be output-dir" => stdout

**Comment by kadel** [comment]
I think that `--output-dir` is OK. Why you want to rename it. Just because `-o -` ?
