### ISSUE TITLE
Add support for imagePullPolicy

### ISSUE THREAD

**Issue by kadel** [redhat-developer/opencompose#84]
Image pull policy. One of Always, Never, IfNotPresent. Defaults to Always if :latest tag is specified, or IfNotPresent otherwise. Cannot be updated. More info: http://kubernetes.io/docs/user-guide/images#updating-images

**Comment by pradeepto** [comment]
Related to https://github.com/redhat-developer/opencompose/issues/122

**Comment by pradeepto** [comment]
Closing as duplicate
